USE TEST;

IF OBJECT_ID('PLAYER') IS NOT NULL
DROP TABLE PLAYER;

IF OBJECT_ID('TURN') IS NOT NULL
DROP TABLE TURN;

GO

CREATE TABLE PLAYER(
USERNAME NVARCHAR(50),     
PRIMARY KEY (USERNAME)
);

CREATE TABLE TURN(
DATETIME DATETIME,
USERNAME NVARCHAR(50), 
PLAYERSELECTION CHAR(1) NOT NULL CHECK (PLAYERSELECTION IN('R','P','S')),
AISELECTION CHAR(1) NOT NULL CHECK (AISELECTION IN('R','P','S')),  
PRIMARY KEY (DATETIME,USERNAME),
FOREIGN KEY (USERNAME) REFERENCES PLAYER
);